apiVersion: v1
kind: Service
metadata:
  name: voting-app
  labels:
    name: voting-app-service
    app: demo-voting-app
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30005
  selector:
    name: voting-app-pod
    app: demo-voting-app